name: Deployment (Test)

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
      - uses: actions/upload-artifact@master
        with:
          name: result
          path: dist/

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: prepare
        uses: actions/checkout@v4

      - name: load dist contents
        uses: actions/download-artifact@master
        with:
          name: result
          path: dist/

      - name: FTP-Upload
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: test.vimfo.org
          username: vimfo_test
          password: ${{ secrets.FTP_PASSWORD_TEST }}
          local-dir: dist/vim-cheatsheet/browser/
          server-dir: /
    needs: [build]
