name: Project-Tests

on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  test:
    name: Testing with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm run test-cov-headless
      - name: lint-test project
        run: npm run lint
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  run-format:
    name: Format Code
    runs-on: ubuntu-latest
    if: ${{ contains(github.head_ref, 'renovate/prettier') }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: install dependencies
        run: npm ci
      - name: format project
        run: npm run format
      - name: commit format changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'OpenFoxes Renovate Helper'
          git config --global user.email 'mail@bono-fox.de'
          git commit -am "🎨 #42: Reformatted code"
          git push
