name: Project-Tests

on: [pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  run-format:
    name: Format Code
    runs-on: ubuntu-latest
    if: ${{ contains(github.head_ref, 'renovate/prettier') }}
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: format project
        run: npm run format
      - name: commit format changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'OpenFoxes Renovate Helper'
          git config --global user.email 'mail@bono-fox.de'
          git commit -am "🎨 #42: Reformatted code"
          git push
  show-ref:
    name: Show REF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: show
        run: console.log(${{ github.head_ref }})
